### ISSUE TITLE
Seen aircraft IF loop fails for 1 previous occasion.

### ISSUE THREAD

**Issue by biohead** [derektgardner/AboveHartland#9]
When determining whether previously seen aircraft has been seen once before or multiple times (dictating whether to use time or times) the IF check fails for a single previous instance since switch to SQL. This results in tweets with the grammatically incorrect "seen 1 times before".

https://github.com/derektgardner/AboveHartland/blob/8ff914223590edddb9a336795dbef7ba0c871ddd/tracker.py#L115
Possible fix is that code could be amended to `if count == '1':`

**Comment by derektgardner** [comment]
I've been unable to replicate this issue. Have you made any other changes to the code? Looking at [AboveBracknell](https://github.com/biohead/AboveBracknell), it looks like your code is very different than what I forked.

**Comment by derektgardner** [comment]
I'm sorry, I think I may have misunderstood your issue. 

@biohead Will it tweet "This is the first time I've seen this aircraft!"? And then the next time it'll say "I've seen this aircraft 1 times before!"?

**Comment by derektgardner** [comment]
I think your fix should work.

With 

https://github.com/derektgardner/AboveHartland/blob/8ff914223590edddb9a336795dbef7ba0c871ddd/tracker.py#L115

I used the integer 1 instead of a string. I converted it to a string here:
https://github.com/derektgardner/AboveHartland/blob/8ff914223590edddb9a336795dbef7ba0c871ddd/tracker.py#L113

I've put your update onto my machine and created a new SQL DB. Now we wait and see when an aircraft comes by twice.

**Comment by biohead** [comment]
Yep that's it.  I wasn't sure if it was something I'd done during porting, but I managed to see the same on your bot (https://twitter.com/AboveHartland/status/1425517835082768388). Realised it was now a string but still being compared to an Int.

Nice and simple at least!

**Comment by derektgardner** [comment]
Fixed. Thanks @biohead!
